name: Publish to NPM

on:
  release:
    types: [published]

jobs:
  publish:
    if: github.event.release.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Clean install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Publish alpha
        if: github.event.release.prerelease && endsWith(github.event.release.tag_name, '-alpha')
        run: npm publish --tag alpha
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish beta
        if: github.event.release.prerelease && endsWith(github.event.release.tag_name, '-beta')
        run: npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish latest
        if: github.event.release.prerelease == false
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
