name: Publish to NPM

on:
  release:
    types: [published]

jobs:
  publish:
    if: github.event.release.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NPM
        uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.0.13'

      - name: Bun install
        run: bun install

      - name: Build
        run: bun run build

      - name: Publish alpha
        if: github.event.release.prerelease && endsWith(github.event.release.tag_name, '-alpha')
        run: npm publish --tag alpha
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish beta
        if: github.event.release.prerelease && endsWith(github.event.release.tag_name, '-beta')
        run: npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish latest
        if: github.event.release.prerelease == false
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
